version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: rest-api-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rest_api_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rest-api-network

volumes:
  postgres_data:

networks:
  rest-api-network:
    driver: bridge
